### ISSUE TITLE
Add i18n support for world languages like Spanish, etc.

### ISSUE THREAD

**Issue by fernando-cm** [freeCodeCamp/mobile#1] opened 2021-02-20 01:06 UTC
I would like you to add the Spanish language.

**Comment by nikunjdk** [comment] 2021-03-23 19:06
There is an option to change to the Spanish language in the app but according to the google play store reviews the app crashes while changing the language. I am not able to reproduce the issue on my device so I don't know where the problem lies but there must be an issue since many users have complained about it. If anybody runs into the problem then do post the stack trace so that I can identify and try to solve the issue.

**Comment by nhcarrigan** [comment] 2021-03-23 19:16
Hey nikunjdk,

Are you referring to the option in the `Menu` dropdown from our native header? With the Spanish and Chinese selections. 
I tested both of those on my end and was also unable to reproduce any errors.

**Comment by nikunjdk** [comment] 2021-03-23 19:33
That's the issue. It is not commonly reproducable but is present for maybe specific devices.

**Comment by raisedadead** [comment] 2021-04-29 15:37
We starting off with a clean slate and will rethinking this mobile app ground up. I am going to close this issue in favor of the direction we are taking, where the app is not just a web view but a feature rich tool at your disposal.

**Closed by raisedadead** 2021-04-29 15:37 UTC
Labels: type: bug, type: feature request
